// <auto-generated />
using System;
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241031193457_dfasdf")]
    partial class dfasdf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.Models.Post", b =>
                {
                    b.Property<uint>("IdPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdPost"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("IdUsuario")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<uint?>("UsuarioIdUsuario")
                        .HasColumnType("int unsigned");

                    b.HasKey("IdPost");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("BackEnd.Models.RolUsuario", b =>
                {
                    b.Property<uint>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdRol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("RolUsuario");
                });

            modelBuilder.Entity("BackEnd.Models.Seguidor", b =>
                {
                    b.Property<uint>("IdUsuario")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("IdUsuarioSeguido")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("FechaSeguimiento")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdUsuario", "IdUsuarioSeguido");

                    b.HasIndex("IdUsuarioSeguido");

                    b.ToTable("Seguidor");
                });

            modelBuilder.Entity("BackEnd.Models.Usuario", b =>
                {
                    b.Property<uint>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FotoPerfil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("IdRol")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("BackEnd.Models.UsuarioLikes", b =>
                {
                    b.Property<uint>("IdUsuario")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("IdPost")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("PostIdPost")
                        .HasColumnType("int unsigned");

                    b.HasKey("IdUsuario", "IdPost");

                    b.HasIndex("IdPost");

                    b.HasIndex("PostIdPost");

                    b.ToTable("UsuarioLikes");
                });

            modelBuilder.Entity("BackEnd.Models.Post", b =>
                {
                    b.HasOne("BackEnd.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Usuario", null)
                        .WithMany("Posteos")
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackEnd.Models.Seguidor", b =>
                {
                    b.HasOne("BackEnd.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Usuario", "UsuarioSeguido")
                        .WithMany()
                        .HasForeignKey("IdUsuarioSeguido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioSeguido");
                });

            modelBuilder.Entity("BackEnd.Models.Usuario", b =>
                {
                    b.HasOne("BackEnd.Models.RolUsuario", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("BackEnd.Models.UsuarioLikes", b =>
                {
                    b.HasOne("BackEnd.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("IdPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Post", null)
                        .WithMany("ListLikes")
                        .HasForeignKey("PostIdPost");

                    b.Navigation("Post");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackEnd.Models.Post", b =>
                {
                    b.Navigation("ListLikes");
                });

            modelBuilder.Entity("BackEnd.Models.Usuario", b =>
                {
                    b.Navigation("Posteos");
                });
#pragma warning restore 612, 618
        }
    }
}
